In [4]:
import cv2
import numpy as np

# Load the image using OpenCV
image_path_cv = 'C:\\Users\\mason\\Pictures\\Screenshots\\Screenshot 2025-01-11 143807.png'
cv_image = cv2.imread(image_path_cv, cv2.IMREAD_GRAYSCALE)

# Apply adaptive thresholding to binarize the image
thresh = cv2.adaptiveThreshold(cv_image, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)

# Detect horizontal and vertical lines
horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (40, 1))  # Horizontal kernel
vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 20))   # Vertical kernel

# Dilate to enhance line detection
horizontal_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel, iterations=2)
vertical_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, vertical_kernel, iterations=2)

# Combine horizontal and vertical lines to create grid
grid = cv2.add(horizontal_lines, vertical_lines)

# Superimpose the grid on the original image to make grid lines visible
grid_lines = cv2.bitwise_or(cv_image, grid)

# Save the image with grid lines for review
grid_lines_path = 'C:\\Users\\mason\\td\\td\\td\\grid_lines.png'
cv2.imwrite(grid_lines_path, grid_lines)

grid_lines_path

'C:\\Users\\mason\\td\\td\\td\\grid_lines.png'

In [10]:
df_result.head()

  Symbol   Bid   Ask  Price  TPrice  Volume      OI NS
0   NVDA  2.76  3.15   2.93     0.0  7676.0  2953.0  W

In [5]:
import cv2
import numpy as np

def draw_gridlines(input_path, output_path):
    # Load the image
    image = cv2.imread(input_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply adaptive thresholding
    thresh = cv2.adaptiveThreshold(
        gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2
    )

    # Detect horizontal lines
    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (40, 1))
    horizontal_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel, iterations=2)

    # Detect vertical lines
    vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 20))
    vertical_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, vertical_kernel, iterations=2)

    # Combine horizontal and vertical lines to get the grid
    grid = cv2.add(horizontal_lines, vertical_lines)

    # Convert grid to 3-channel image (to overlay on the original image)
    grid_colored = cv2.cvtColor(grid, cv2.COLOR_GRAY2BGR)

    # Overlay the grid on the original image
    combined = cv2.addWeighted(image, 0.8, grid_colored, 0.2, 0)

    # Save the output image
    cv2.imwrite(output_path, combined)

# Example usage
input_image_path = 'C:\\Users\\mason\\td\\td\\td\\grid_lines.png'
output_image_path = 'C:\\Users\\mason\\td\\td\\td\\grid_lines_with_output.png'
draw_gridlines(input_image_path, output_image_path)

In [72]:
import cv2
import numpy as np

def draw_fixed_gridlines(input_path, output_path, horizontal_lines, vertical_lines):
    # Load the image
    image = cv2.imread(input_path)

    # Create a copy to draw gridlines
    grid_image = image.copy()

    # Draw horizontal lines
    for y in horizontal_lines:
        cv2.line(grid_image, (0, y), (grid_image.shape[1], y), (0, 0, 255), 1)  # Red lines for visibility

    # Draw vertical lines
    for x in vertical_lines:
        cv2.line(grid_image, (x, 0), (x, grid_image.shape[0]), (0, 0, 255), 1)  # Red lines for visibility

    # Save the output image
    cv2.imwrite(output_path, grid_image)

# Example usage
input_image_path = 'C:\\Users\\mason\\td\\td\\td\\grid_lines.png'
output_image_path = 'C:\\Users\\mason\\td\\td\\td\\grid_lines_with_fixed_output.png'

# Specify exact pixel locations for horizontal and vertical gridlines
horizontal_lines = [35, 65, 95, 120, 150, 180, 205, 231, 258, 290, 317, 345, 370]  # Example y-coordinates
vertical_lines = [50, 95, 155, 205, 255, 305, 355, 410, 445, 490, 550, 600, 650, 700, 750]  # Example x-coordinates

draw_fixed_gridlines(input_image_path, output_image_path, horizontal_lines, vertical_lines)

In [76]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('C:\\Users\\mason\\td\\table-1.csv')

# Clean up column names by removing extra quotes and apostrophes
df.columns = df.columns.str.strip("'")

# Clean up data values by removing extra quotes and apostrophes 
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].str.strip("'")

# Convert numeric columns to appropriate types
numeric_cols = ['Strike', 'Bid', 'Ask', 'Price', 'TPrice', 'Volume', 'IVol', 
                'Delta', 'Theta', 'Gamma', 'Vega', 'Rho']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [77]:
df.head()

,Strike,Symbol,Bid,Ask,Price,TPrice,Volume,or,NS,IVol,Delta,Theta,Gamma,Vega,Rho,Strike.1,Unnamed: 16
0,132.0,NVDA,3.65,4.05,3.90,0.0,3439.0,2886,W,2.3569,0.0,0.0,0.0,0.0,0.0,132,NaN
1,133.0,NVDA,2.76,3.15,2.93,0.0,7676.0,2953,W,2.3569,0.0,0.0,0.0,0.0,0.0,133,NaN
2,134.0,NVDA,1.77,2.11,2.09,0.0,23589.0,4100,W,2.3569,0.0,0.0,0.0,0.0,0.0,134,NaN
3,135.0,NVDA,0.79,1.10,0.95,0.0,107179.0,7970,W,2.3569,0.0,0.0,0.0,0.0,0.0,135,NaN
4,136.0,NVDA,0.03,0.04,0.03,0.0,230724.0,8673,W,2.3569,0.0,0.0,0.0,0.0,0.0,136,NaN

In [80]:
# Read the CSV file
df = pd.read_csv('C:\\Users\\mason\\td\\td\\table-1.csv')

# Clean up column names by removing extra quotes and apostrophes
df.columns = df.columns.str.strip("'")

# Clean up data values by removing extra quotes and apostrophes
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].str.strip("'")

# Convert numeric columns to appropriate types
numeric_cols = ['Strike', 'Bid', 'Ask', 'Price', 'TPrice', 'Volume', 'OI']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [81]:
df.head()

,Symbol,Bid,Ask,Price,TPrice,Volume,OI,NS,Strike,Symbol.1,Bid.1,Ask.1,Price.1,TPrice.1,Volume.1,OI.1,NS.1,Unnamed: 17
0,NVDA,4.15,4.25,4.20,12.43,28606,2950,S,131,NVDA,1.85,1.91,1.87,10.16,46468,11574,S,NaN
1,NVDA,3.55,3.65,3.60,11.95,67608,19544,S,132,NVDA,2.24,2.29,2.25,10.68,35807,20713,S,NaN
2,NVDA,3.00,3.10,3.10,11.48,58567,2030,S,133,NVDA,2.64,2.73,2.66,11.21,15145,8966,S,NaN
3,NVDA,2.51,2.55,2.56,11.03,25336,13978,S,134,NVDA,3.10,3.25,3.20,11.76,6252,18568,S,NaN
4,NVDA,2.06,2.10,2.09,10.59,93909,59273,S,135,NVDA,3.65,3.80,3.75,12.32,15504,42966,S,NaN